export const isolationLevelQueries = {
    readUncommitted: 'SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;',
    readCommitted: 'SET TRANSACTION ISOLATION LEVEL READ COMMITTED;',
    repeatableRead: 'SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;',
    serializable: 'SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;'
}